apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment
  template:
    metadata:
      labels:
        app: payment
    spec:
      containers:
      - name: payment
        image: payment
        imagePullPolicy: Never
        env:
        - name: DB_PATH
          value: /data/payments.db
        - name: TRIP_SERVICE_URL
          valueFrom:
            configMapKeyRef:
              name: platform-config
              key: TRIP_SERVICE_URL
        - name: RABBITMQ_URL
          valueFrom:
            configMapKeyRef:
              name: platform-config
              key: RABBITMQ_URL
        - name: EVENTS_EXCHANGE
          valueFrom:
            configMapKeyRef:
              name: platform-config
              key: EVENTS_EXCHANGE
        - name: PAYMENT_QUEUE
          valueFrom:
            configMapKeyRef:
              name: platform-config
              key: PAYMENT_QUEUE
        ports:
        - containerPort: 3000

        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "200m"
            memory: "256Mi"
        livenessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 10
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 5
        volumeMounts:
        - name: payment-storage
          mountPath: /data
      volumes:
      - name: payment-storage
        persistentVolumeClaim:
          claimName: payment-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: payment
spec:
  selector:
    app: payment
  ports:
    - port: 3000
      targetPort: 3000
  type: ClusterIP
