apiVersion: v1
kind: ConfigMap
metadata:
  name: platform-config
data:
  DRIVER_SERVICE_URL: http://driver:3000
  PAYMENT_SERVICE_URL: http://payment:3000
  NOTIFICATION_SERVICE_URL: http://notification:3000
  TRIP_SERVICE_URL: http://ride:3000
  RABBITMQ_URL: amqp://rabbitmq:5672
  EVENTS_EXCHANGE: ride.events
  PAYMENT_QUEUE: payment.queue
  NOTIFICATION_QUEUE: notification.queue
  CANCELLATION_FEE: "30"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: user-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: driver-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ride-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: payment-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rating-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
