apiVersion: apps/v1
kind: Deployment
metadata:
  name: rating
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rating
  template:
    metadata:
      labels:
        app: rating
    spec:
      containers:
      - name: rating
        image: rating
        imagePullPolicy: Never
        ports:
        - containerPort: 3000
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "200m"
            memory: "256Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: rating
spec:
  selector:
    app: rating
  ports:
    - port: 3000
      targetPort: 3000
  type: ClusterIP
